### ISSUE TITLE
Global variables

### ISSUE THREAD

**Issue by TBardachova** [pabloconrat/our_first_climate_model#1]
Put physical parameters in to a class/struct instead of defining them as global variables.

**Comment by TBardachova** [comment]
I have found two ways how we can define physical constants using class or struct instead of defining them as global variables. As I understood one of them is more common way how it usually implements in C++. Another one is more "Python" way. I add both of them to code, so we can decide what is better for us. 
"C++" way: probably more correct, but has longer initialization of constants, in "main" we call constants using "::" (for example: heating(theta, dp, con::E_abs, dt, con::g, con::c_air, t_to_theta))
"Python" way: shorter initialization and in "main" we call constants using "." (heating(theta, dp, con.E_abs, dt, con.g, con.c_air, t_to_theta)
"Python" way looks more familiar for me, but in general I'm okay to use any of them. Do you have some thoughts/preferences about it?
I added my changes to main.cpp in my branch. 
@pabloconrat @samkeyat

**Comment by pabloconrat** [comment]
Hi, I just looked at it and I think the C++ way looks good and quite similar to what the lecturers do in their code so I would pull use that? Could you merge that into the main?

**Comment by TBardachova** [comment]
I added C++ way of constants initialization into main.cpp at master branch.
