### ISSUE TITLE
Output File 

### ISSUE THREAD

**Issue by pabloconrat** [pabloconrat/our_first_climate_model#2]
Adapt the current output function to write out a file adapted to the jupyter notebook presented in class.

**Comment by samkeyat** [comment]
Hello Guys,
I have just uploaded a python script named 'main_plotting_sam.ipynb'. In order to make it run you need to have a 'output.txt' file in your directory. You can generate that file by inserting 'freopen("output.txt","w",stdout);' in the main() function. Thanks.
