### ISSUE TITLE
Make calculation of irradiance for window atmosphere

### ISSUE THREAD

**Issue by TBardachova** [pabloconrat/our_first_climate_model#25]

**Comment by TBardachova** [comment]
Hi, I had a mood for programming yesterday and tried to make calculations for window atmosphere :D 
My results for different tau_total are the same as benchmarks values, but I'm not sure about some things. 

The main problem that I realized is the time of calculation. For dlambda equals 100 it is quite quick, but if we will use dlambda 1 nm it is longer that few minutes and I don't know if it is how it suppose to be. 
Also I'm not sure about tau vector definition. Now I define it as 2d array with size (number of wavelenghts, number of layers), but that I had problems to include tau into our functions radiative_transfer and monochromatic_radiative_transfer. My friend helped me with it, but maybe you will know better way how to do it. 

Also I'm going to put tau calculation as separate function, but it is no ready by now.

You can find the code on my branch. I'm will be happy hear your remarks or ideas of improvements :)

**Comment by pabloconrat** [comment]
Hi, I will try to understand the tau values and how they are stored. Also I have a suggestion on the temperature profile: 
- we initialize a vector with nlevel entries 
- T[nlevel] is the surface temperature and the rest (nlayer entries) are the atmospheric ones

This way we can implement a changing surface temperature in the future without any problem. What do you think?

**Comment by pabloconrat** [comment]
I have an idea for vertically well mixed gases aka. tau being constant in height:

we store a vector of lamdas as we did up to now and additionally a vector with the total taus in this way:
lamdas = {lamda_1, lamda_2, ... , lamda_nlamdas}  -> length = nlamdas
taus = {tau_1, tau_2, ... , tau_ntaus} where ntaus = nlamdas -1 -> length = nlamdas-1

Then in radiative_transfer() before calling the monochromatic function we calculate the (so far constant) vector of taus by:
`
loop over i_rad {
`
`
     vector<double> tau_vector = 1 / taus[i_rad] * vector_of_ones 
`
`
     monochromatic_radiative_transfer(..., tau_vector,...)
}
`

Like this we never have to set up a 2D array as we get the tau values from one vector that *tada* just needs the same index as we already use for the selection of the wavelength window. What do you think?

**Comment by TBardachova** [comment]
So, I fixed integration over wavelengths bands. Now calculations run very quickly. I upload to my branch two versions with a little bit different tau definition (as 2D dynamic array and as vector<vector<double>>), maybe one of them will be useful for us in future :)
