### ISSUE TITLE
T-surface dependence on total tau

### ISSUE THREAD

**Issue by TBardachova** [pabloconrat/our_first_climate_model#35]
Hi, I tried to run our model for different values of total tau (from 0 to 10) to get dependence of T near surface on tau. The T values that I got don't look like right on my opinion. The profiles which was shown in class had logarithmic behavior, but I didn't get similar behavior.
What do you think about it?  Do you thing the values are correct? Or probably we still have some mistakes in our coupling?

There are my values:
tau_t   T-sfc
10.0    557.9
9.0      550.5
8.0      542.7
7.0      534.3
6.0      525.6
5.0      512.7
4.0      497.0
3.0      481.8
2.0      469.2
1.0      464.9
0.0      1118.9

**Comment by TBardachova** [comment]
I tried to add the thermal radiation balance at the ground how prof. Mayer advised to us and now T values seems right. 

tau = 100 : T_low_window = 325.2, T_low_grey = 451.2
tau = 10 : T_low_window = 317.9, T_low_grey = 405.4
tau = 1 : T_low_window = 273.6, T_low_grey = 284.9

**Comment by pabloconrat** [comment]
Hi, cool! I'll check it out
