### ISSUE TITLE
Calculate the dependence of surface temperature on CO2 concentration

### ISSUE THREAD

**Issue by TBardachova** [pabloconrat/our_first_climate_model#43]
Calculate he dependence of surface temperature on CO2 concentration on a logarithmic CO2 scale (0.5 * CO2, 1xCO2, 2*CO2, ...)

**Comment by TBardachova** [comment]
My values:

CO2 concentration [ppm] : temperature near surface [K] : surface temperature [K]

320   :  283.32  :  285.38
400   :  283.83  :  285.89
600   :  284.75  :  286.82
800   :  285.45  :  287.52
1600 :  287.25  :  289.33

**Comment by pabloconrat** [comment]
I added some more values to the table. I think we are good with that :)
