### ISSUE TITLE
Implement parametrization 

### ISSUE THREAD

**Issue by TBardachova** [pabloconrat/our_first_climate_model#46]
Use representative wavelengths instead of full line-by-line spectrum

**Comment by TBardachova** [comment]
Hi :)

I just uploaded the new version of the model on my branch. The parametrization is seems to work, I checked it for some CO2 concentrations. I didn't get the same surface temperature as before (temperatures are 1-2 degrees higher than before), because in this case the initial temperature profile is prescribed by Prof. Mayer (in file test.atm), but we can check it if we put this profile in our line-by-line version. 

I'm not sure about one step in my code, about calculation of Tlevel for recall of read_tau every 50-100 steps. We can discuss it on Monday. 

I also changed files from repwvl_V1.0, I adapted them for cpp and a little bit for our definition of variables. You can find new files in folder repwvl_V1.0_cpp in my branch. In this folder should be all files that we need to run the model.

To run the model in Jupyterhub you should include NetCDF first:
module load netcdf/4.7.0-gcc

Than use this command to compile the code:
g++ -Wall -o test main_weighted.cpp ./repwvl_V1.0_cpp/repwvl_thermal.cpp  -lnetcdf_c++4 -L/opt/local/lib

Feel free to play with it, probably it still has some problems. Now it takes just around 1-2 minutes to get the equilibrium :)

**Comment by pabloconrat** [comment]
Hi Tanya, I don't think the initial profile determines our final temperatures. But we were colder than the other models so I think it's not so much of a problem. But we should ask that on monday. 

Just to make sure I got it right: you are unsure if the amount of timesteps between the calls of read_tau are correct? 

Thanks a lot!

**Comment by TBardachova** [comment]
Hi, I also think that it is not a problem, I just tried to guess what could cause it :)

No, no actually, I meant this part of the code:
// computation of Tlevel for new temperature profile  
Tlevel[0] = T_surface;
Tlevel[1] = (Tlayer[0] + T_surface) / 2.0;
for (int ilyr=0; ilyr<Consts::nlayer-1; ++ilyr) {
..Tlevel[ilyr+2] = (Tlayer[ilyr] + Tlayer[ilyr+1]) / 2.0;
}

For read_tau computation we use Tlevel, not Tlayer, so I calculate it from Tlayer before read_tau calculation. I just wasn't sure if I made it right: T for first level is T-surface now, T for second layer is mean between T-surface and T of first layer, T for other levels is mean between T of two nearest layers. 
Actually I am not sure if we really need to put Tlevel in read_tau, probably if we would put Tlayer instead it also would be correct. We could ask it on Monday.
