### ISSUE TITLE
Solar radiative transfer

### ISSUE THREAD

**Issue by TBardachova** [pabloconrat/our_first_climate_model#47]

**Comment by pabloconrat** [comment]
I uploaded a running version to my branch where the code calculates the solar irradiance before the loop and then uses it in the radiative transfer function. Somehow our planet get's really hot. We have to check this...

**Comment by TBardachova** [comment]
Thanks, I will have a look on it during weekend. Overheating is our typical problem :D

**Comment by pabloconrat** [comment]
Cloud now also included in thermal
