### ISSUE TITLE
Cooling rate for realistic atmospheric profile

### ISSUE THREAD

**Issue by TBardachova** [pabloconrat/our_first_climate_model#8]
Try to adjust the cooling rate so that you obtain a realistic atmospheric profile.

**Comment by pabloconrat** [comment]
I added a cooling rate to my most recent commit so we can play around with it now

**Comment by pabloconrat** [comment]
I stabilized the atmosphere in the long run (~100 000 hours or ~4000 days) to a surface temperature of 290K by prescribing a cooling of -1.475 K/d on the atmosphere. Does this settle this topic?
